# Generated by Django 4.0.4 on 2022-07-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviesdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Story', models.CharField(max_length=255)),
                ('Actor', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=255)),
                ('Budget', models.CharField(max_length=255)),
                ('BoxOfficeCollection', models.CharField(max_length=255)),
            ],
        ),
    ]
